project:
  type: website

website:
  title: "agoralab.ai"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://x.com/AgoraLabAI
      - icon: twitter
        href: https://twitter.com/apac_ai
format:
  html:
    theme: darkly
    css: styles.css

